# Generated by Django 5.2.1 on 2025-07-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('head1', models.CharField(max_length=500)),
                ('subhead1', models.CharField(default='', max_length=5000)),
                ('head2', models.CharField(max_length=500)),
                ('subhead2', models.CharField(default='', max_length=5000)),
                ('head3', models.CharField(max_length=500)),
                ('subhead3', models.CharField(default='', max_length=5000)),
                ('Location', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
