# Generated by Django 5.2.1 on 2025-07-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=50)),
                ('Phone', models.IntegerField(default=0)),
                ('Desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
