# Generated by Django 5.2.1 on 2025-07-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_desc_contact_desc_rename_email_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(default='')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('pincode', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
